export const newslist = [
  {
    title: 'PlayStation Plus Free Games For September 2022 Revealed',
    imageURL: require('../img/4029176-ps-plus-sep-logo-promo1-2-thumb-1.jpg'),
    fullNews: "Following a leak, PlayStation has confirmed the next batch of PlayStation Plus freebies. September 2022's PS Plus Essential lineup will include Need for Speed Heat, Toem, and Granblue Fantasy: Versus. All three of those games are worth playing, so it'll be a pretty good month overall for freebies on PlayStation. The new batch of games will be available to claim starting September 6. As a reminder, all PS Plus subscribers, regardless of tier, can claim the PlayStation Plus Essential lineup each month. More games are also available for Extra and Premium members.Need for Speed Heat is the best-known game of the bunch. It's the latest entry (not including remasters) in the long-running EA racing franchise and a turn in the right direction. The franchise went down a bumpy road throughout the 2010s, but Need for Speed Heat recaptured the pure arcade racing fun that the series was known for in its early days. Featuring a cool night-and-day system in which you compete in sanctioned events by day and illegal street races after dark, Need for Speed Heat offers a decent amount of variety that keeps the arcade racing fresh throughout its roughly 10-hour runtime. It earned a 7/10 in our Need for Speed Heat review. Need for Speed Heat doesn't have a PS5 upgrade, but you can play it on the latest PlayStation console via backwards compatibility.Toem is a charming indie that released just last year. You play as a young photographer in search of a snapshot of the eponymous Toem phenomenon. If you're looking for a relaxing game that won't take up too much time, Toem is a good choice. The gameplay revolves around solving puzzles by taking photographs of the world around you. The black-and-white visuals are lovely, and the gameplay is complemented by a beautiful soundtrack. Only the PS5 version of Toem will be available to claim in September.Fighting game fans can check out Granblue Fantasy: Versus, a 2.5D fighting game developed by Arc System Works. Featuring the characters that first appeared in the Granblue Fantasy mobile game in 2014, Versus is a stylish fighter with great mechanics. It also implements RPG systems, which is fitting considering the first Granblue Fantasy game was an RPG. The single-player campaign isn't very exciting, but the core fighting mechanics are great. It earned a 7/10 in our Granblue Fantasy: Versus review.If you haven't already, make sure to claim August's freebies before they leave PlayStation Plus on September 6. August's lineup includes Yakuza: Like a Dragon, Tony Hawk's Pro Skater 1 + 2, and Little Nightmares.PlayStation is also adding new games to the PS Plus Extra/Premium library next month, including Deathloop, Chicory: A Colorful Tale, and Assassin's Creed Origins.",
    isBigNews: true,
    id: 1,
    dateOfWriting: new Date(2022,8,4,12,15),
    tag: 'Console',
  },
  {
    title: 'Xbox Games With Gold Free Games For September 2022 Revealed',
    imageURL: require('../img/4028692-xbox-games-gold-sept-promo1-2-thumb-1.jpg'),
    fullNews: "We're at the start of another new month, so that means that it's time to claim some freebies on Xbox Store--if you're a Game Pass Ultimate or Xbox Live Gold subscriber, of course. September's Games with Gold lineup currently features Gods Will Fall and Thrillville. You can also still claim one of August's freebies, ScourgeBringer, until September 16. Halfway through the month the lineup will refresh with Double Kick Heroes and Portal 2.   As a reminder, it's the last month for original Xbox and Xbox 360 freebies in the Games with Gold program. But keep in mind that you will be able to keep all of the backwards compatible games you've claimed up until now, even if your Xbox Live Gold subscription lapses. That means Portal 2 will be free to keep, which is pretty cool.    Portal 2 is the star of the show in September. The classic puzzle-shooter is widely considered to be one of the best games of its era. The sequel expanded greatly on the already-brilliant foundation of the original. Featuring a campaign that's roughly double the length of its predecessor, Portal 2 added some seriously great mechanics to the formula. If you've never played Portal 2, do yourself a favor and check it out next month. It even has a separate cooperative campaign that you can play alongside a friend. Portal 2 will be free in the back half of September.Prior to Portal 2 landing on the service, you can add Thrillville to your Xbox library. Thrillville is an amusement park management sim that originally released in 2006. If you've ever played Rollercoaster Tycoon, Thrillville isn't all that different, but it does have an actual narrative. Along with managing the park's day-to-day activities, you have to complete missions to move on. There are five parks in total to oversee. Thrillville also has a bunch of mini-games that can be played solo or with friends. You can grab Thrillville until September 15.We started with the backwards-compatible classics because they are just a bit more exciting than the Xbox One games for September. All month long subscribers will be able to claim Gods Will Fall, an action game that released last year. You play as a Celtic warrior in a fight against a numerous gods that control the world. Gods Will Fall does offer an interesting spin on the roguelike genre and features challenging combat, so it's worth checking out if you like those sorts of action games.",
    isBigNews: true,
    id: 2,
    dateOfWriting: new Date(2022,8,4,12,12),
    tag: 'Console',
  },
]